define(['hogan'], function(Hogan) {
  var t = {
    'CronView' : new Hogan.Template(function(c,p,i){var _=this;_.b(i=i||"");_.b("<div class=\"field-group cron\">");_.b("\n" + i);_.b("    <label for=\"expression-");_.b(_.v(_.f("cid",c,p,0)));_.b("\">");_.b(_.v(_.f("type",c,p,0)));_.b(" <span class=\"aui-icon icon-required\"> required</span></label>");_.b("\n" + i);_.b("    <input class=\"text long-field\" type=\"text\" value=\"");_.b(_.v(_.f("expression",c,p,0)));_.b("\" name=\"expression\" id=\"expression-");_.b(_.v(_.f("cid",c,p,0)));_.b("\">");_.b("\n" + i);_.b("    <select name=\"operation-");_.b(_.v(_.f("cid",c,p,0)));_.b("\" class=\"operation select\">");_.b("\n" + i);if(_.s(_.f("operations",c,p,1),c,p,0,337,396,"{{ }}")){_.rs(c,p,function(c,p,_){_.b("        <option value=\"");_.b(_.v(_.f("id",c,p,0)));_.b("\">");_.b(_.v(_.f("name",c,p,0)));_.b("</option>");_.b("\n");});c.pop();}_.b("    </select>");_.b("\n" + i);if(_.s(_.f("removable",c,p,1),c,p,0,444,610,"{{ }}")){_.rs(c,p,function(c,p,_){_.b("        <button class=\"aui-button aui-button-subtle remove\" data-cid=\"");_.b(_.v(_.f("cid",c,p,0)));_.b("\"><span class=\"aui-icon aui-icon-small aui-iconfont-remove\"></span> Remove</button>");_.b("\n");});c.pop();}_.b("</div>");_.b("\n");return _.fl();;}),
    'TabCollectionView' : new Hogan.Template(function(c,p,i){var _=this;_.b(i=i||"");_.b("<form class=\"aui\">");_.b("\n" + i);_.b("    <div class=\"tabs\"></div>");_.b("\n" + i);_.b("	<div class=\"buttons-container\">");_.b("\n" + i);_.b("		<div class=\"buttons\">");_.b("\n" + i);_.b("			<button class=\"aui-button aui-button-primary save\"><span class=\"aui-icon aui-icon-small aui-iconfont-success\"></span> Save</button>");_.b("\n" + i);_.b("			<button class=\"aui-button add\"><span class=\"aui-icon aui-icon-small aui-iconfont-add\"></span> Add Tab</button>");_.b("\n" + i);_.b("		</div>");_.b("\n" + i);_.b("	</div>");_.b("\n" + i);_.b("</form>");_.b("\n");return _.fl();;}),
    'TabView' : new Hogan.Template(function(c,p,i){var _=this;_.b(i=i||"");_.b("<fieldset data-tab-cid=");_.b(_.v(_.f("cid",c,p,0)));_.b(">");_.b("\n" + i);_.b("	<div class=\"field-group\">");_.b("\n" + i);_.b("		<label for=\"url-");_.b(_.v(_.f("cid",c,p,0)));_.b("\">URL <span class=\"aui-icon icon-required\"> required</span></label>");_.b("\n" + i);_.b("		<input class=\"text long-field url\" id=\"url-");_.b(_.v(_.f("cid",c,p,0)));_.b("\" type=\"text\" name=\"url\" value=\"");_.b(_.v(_.f("url",c,p,0)));_.b("\" />");_.b("\n" + i);_.b("	</div>");_.b("\n" + i);_.b("	<div class=\"crons\"></div>");_.b("\n" + i);_.b("	<div class=\"buttons-container\">");_.b("\n" + i);_.b("        <button class=\"aui-button aui-button-subtle addSchedule\" data-type=\"cron\"><span class=\"aui-icon aui-icon-small aui-iconfont-add\"></span> Add Cron</button>");_.b("\n" + i);_.b("        <button class=\"aui-button aui-button-subtle addSchedule\" data-type=\"text\"><span class=\"aui-icon aui-icon-small aui-iconfont-add\"></span> Add Text Expression</button>");_.b("\n" + i);_.b("	</div>");_.b("\n" + i);if(_.s(_.f("removable",c,p,1),c,p,0,679,917,"{{ }}")){_.rs(c,p,function(c,p,_){_.b("        <div class=\"buttons-container\">");_.b("\n" + i);_.b("            <button class=\"aui-button remove\" data-cid=\"");_.b(_.v(_.f("cid",c,p,0)));_.b("\"><a class=\"aui-icon aui-icon-small aui-iconfont-remove\" href=\"\" data-cid=\"");_.b(_.v(_.f("cid",c,p,0)));_.b("\">Remove</a> Remove Tab</button>");_.b("\n" + i);_.b("        </div>");_.b("\n");});c.pop();}_.b("</fieldset>");_.b("\n");return _.fl();;})
  },
  r = function(n) {
    var tn = t[n];
    return function(c, p, i) {
      return tn.render(c, p || t, i);
    };
  };
  return {
    'CronView' : r('CronView'),
    'TabCollectionView' : r('TabCollectionView'),
    'TabView' : r('TabView')
  };
});
